- Alias: sleep
  Usage: sleep [interval] <jitter>
  Module: Core
  Command: Sleep
  Parameters:
  - Name: Interval
    Type: Integer
  - Name: Jitter
    Type: Integer
- Alias: load-module
  Usage: load-module [path]
  Module: Core
  Command: LoadModule
  Parameters:
  - Name: Path
    Type: String
  - Name: Assembly
    Type: File
- Alias: exit
  Usage: exit
  Module: Core
  Command: Exit