- Alias: link-tcp
  Description: Link to a TCP Agent
  Usage: link-tcp [target] [port]
  OpSec: Inline
  Module: Link
  Command: TCP
  Parameters:
  - Name: Target
    Type: String
  - Name: Port
    Type: Integer